language: go

go: 
 - 1.8
 - 1.9
 - tip


jobs:
  include:
    - stage: test
      script: go test $(go list ./... | grep -v /vendor/) -cover -tags test -race
    - stage: build
      script: go build -o goproxy.o